### ISSUE TITLE
Update please

### ISSUE THREAD

**Issue by sergeevabc** [n6333373/sublime-self-patcher#2]
Dear @n6333373, SelfPatcher no longer works with build 4177.
Could you be so kind to update it?

**Comment by n6333373** [comment]
It looks like @bad1dea's "any grammatical license patch pattern" no longer works for Sublime Text 4177 Windows build. 

Hi @bad1dea, are you still interested in finding a new one, I can provide a working legit license if that would make your journey easier.

**Comment by n6333373** [comment]
Nvm. I've found the new pattern by myself. I am still willing to provide you a legit license if you want one. I will update SelfPatcher soon.

**Comment by n6333373** [comment]
Done.

**Comment by sergeevabc** [comment]
Thank you, @n6333373. It works as expected.
