### ISSUE TITLE
The menu item "Patch This Application" is grayed out

### ISSUE THREAD

**Issue by 8Observer8** [n6333373/sublime-self-patcher#3]
The menu item "Patch This Application" appeared in "Help", but it is inactive, that is, gray and I can not click on it. I tried versions 4180, 4169 and 4152 - all the same result with a gray item "Patch This Application"

**Comment by n6333373** [comment]
either it is a unsupported platform or you didnt do plugin installation right.

**Comment by 8Observer8** [comment]
Sorry, I didn't write what platform I use. It is Windows 7, 32-bit, SP1

My steps:

- I download and install Sublime Text 4180: https://download.sublimetext.com/sublime_text_build_4180_x32_setup.exe
- I copied the "SelfPatcher" folder to the "C:\Users\User\AppData\Roaming\Sublime Text\Packages" folder
- I ran "sublime_text.exe"
- I pressed in the menu: "Help" > "Patch This Application". But "Patch This Application" is inactive

Please write what I can try. I will try any actions you write.

**Comment by n6333373** [comment]
> Sorry, I didn't write what platform I use. It is Windows 7, 32-bit, SP1

Oops, I didn't actually test this plugin on Win7 and it's compiled on Win10. 
I guess there will be some error message in Sublime Text's console (`` ctrl+` ``) when starting up?

I will setup a Win7 x32 VM to test this later when I am available.

---------------------

Here are patched 4180 and 4183 binaries:
[st_patched.zip](https://github.com/user-attachments/files/17141861/st_patched.zip)

**Comment by n6333373** [comment]
Temporarily you can use a modern machine (Win10/11, Linux x64) to patch it and move patched binary to your Win7 machine.

A portable Win x32 build can be downloaded with https://download.sublimetext.com/sublime_text_build_4180.zip

**Comment by 8Observer8** [comment]
> Here are patched 4180 (stable) and 4183 (dev) Sublime Text binaries: [st_patched.zip](https://github.com/user-attachments/files/17141861/st_patched.zip)
I replaced EXE of installed 4180. "Patch This Application" is still inactive.

A portable Win x32 build can be downloaded from https://download.sublimetext.com/sublime_text_build_4180.zip (you can change the version number in this link to the version you want)
I moved the "SelfPatcher" folder to the "Data\Packages\" folder but "Patch This Application" is still inactive.

**Comment by 8Observer8** [comment]
> At this moment, you can use a modern machine (Win10/11, Linux x64) to patch it and move patched binary onto your Win7 x32 machine.

It works! Thank you very much!

Steps from scratch:

- Use Windows 10 64 bit to patch 32 bit version of Sublime Text 4
- Download a portable Win x32 build can be downloaded from https://download.sublimetext.com/sublime_text_build_4180.zip (you can change the version number in this link to the version you want)
- Download the "SelfPatcher" folder: https://github.com/n6333373/sublime-self-patcher
- Run the "sublime_text.exe" to generate the "Data\Packages" folder
- Close "Sublime Text 4"
- Copy the "SelfPatcher" folder to the "Data\Packages" folder
- Run the "sublime_text.exe"
- Go to menu > "Help" > and press "Patch This Application" > "Ok" > "Ok"
- Close "Sublime Text 4" and run it again
- Done

**Comment by 8Observer8** [comment]
@n6333373 I am ready to test pre-release patches at any time to fix this bug.

**Comment by n6333373** [comment]
I have pushed a new commit for it and tested working on Win7 32-bit.

**Comment by 8Observer8** [comment]
The new commit didn't help:

![image](https://github.com/user-attachments/assets/8f3145f5-09b8-4804-9ccf-4ef94e48a01c)

**Comment by n6333373** [comment]
> The new commit didn't help:
> 
> ![image](https://private-user-images.githubusercontent.com/3908473/371599206-8f3145f5-09b8-4804-9ccf-4ef94e48a01c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NjMwNTAsIm5iZiI6MTcyNzQ2Mjc1MCwicGF0aCI6Ii8zOTA4NDczLzM3MTU5OTIwNi04ZjMxNDVmNS0wOWI4LTQ4MDQtOWNjZi00ZWY5NGU0OGEwMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjdUMTg0NTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTBkNWMyOTZlZjQ2MTA1YjM5OTA5MTM5NmMwZDA3NGM5MDZiZmI0ODIyMDJhZDUyYjlhMTk3N2U5MTA3ZmQyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2LEMATCNoHnkSYEFPX0omu2JxhDothmqf8ZdI2k5l3E)

See console for any error message

**Comment by 8Observer8** [comment]
Console output:

```
reloading plugin SelfPatcher.boot
[SelfPatcher][INFO] The current platform-arch is unsupported.
plugins loaded
```

Full log:

```
DPI mode: system
DPI scale: 1
startup, version: 4180 windows x32 channel: stable
executable: /C/Program Files/Sublime Text/sublime_text.exe
application: /C/Program Files/Sublime Text
working dir: /C/Program Files/Sublime Text
packages path: /C/Users/root/AppData/Roaming/Sublime Text/Packages
state path: /C/Users/root/AppData/Roaming/Sublime Text/Local
zip path: /C/Program Files/Sublime Text/Packages
zip path: /C/Users/root/AppData/Roaming/Sublime Text/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 1.98005
startup time: 2.17505
first paint time: 2.30005
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin SelfPatcher.boot
[SelfPatcher][INFO] The current platform-arch is unsupported.
plugins loaded
```

**Comment by n6333373** [comment]
> [SelfPatcher][INFO] The current platform-arch is unsupported.

I have added a new commit to show more detailed error message about this.

**Comment by 8Observer8** [comment]
```
[SelfPatcher][INFO] The current platform-arch is unsupported: DLL load failed while importing plugin: The parameter is set incorrectly.
```

**Comment by n6333373** [comment]
> > [SelfPatcher][INFO] The current platform-arch is unsupported: DLL load failed while importing plugin: The parameter is set incorrectly.

Are you able to update your OS to Service Pack 2?

## Related Resources

- https://github.com/streamlink/streamlink/issues/3332#issuecomment-734043762
- https://answers.microsoft.com/en-us/windows/forum/windows_7-update/how-to-obtain-and-install-windows-7-sp2/c2c7009f-3a10-4199-9c89-48e1e883051e

**Comment by 8Observer8** [comment]
Thank you very much! The SP2 solved the problem. But "sublime_text.exe" must be run as administrator because in another case you will see "Access denied":

![image](https://github.com/user-attachments/assets/93d20b94-a451-4148-81e8-66bb0abb8fde)

If the "Patch This Application" is still grayed out make the "View" > "Show Console" > "Hide Console"

![image](https://github.com/user-attachments/assets/81ae7b1f-5d5f-4da6-a190-d356e9a7b6ea)

![image](https://github.com/user-attachments/assets/2a65c014-015e-4590-9ce4-63a98ab80ba8)

![image](https://github.com/user-attachments/assets/248e29a1-2223-4bd4-8cf5-4a0c03e9ff7c)

Console output:

```
DPI mode: system
DPI scale: 1
startup, version: 4180 windows x32 channel: stable
executable: /C/Program Files/Sublime Text/sublime_text.exe
application: /C/Program Files/Sublime Text
working dir: /C/Program Files/Sublime Text
packages path: /C/Users/root/AppData/Roaming/Sublime Text/Packages
state path: /C/Users/root/AppData/Roaming/Sublime Text/Local
zip path: /C/Program Files/Sublime Text/Packages
zip path: /C/Users/root/AppData/Roaming/Sublime Text/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 28.8775
startup time: 30.7475
first paint time: 30.8105
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.html_print
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.keymap
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin SelfPatcher.boot
plugins loaded
```

**Comment by n6333373** [comment]
> But "sublime_text.exe" must be run as administrator because in another case you will see "Access denied":

That's inevitable because it's installed on `C:`. So self-patching can't overwrite to `C:` without admin permission. 

You can use `Patch External Sublime Text/Merge` instead. That will output patched executable and license file to a temp folder. And then you just copy them to where it should be.
