### ISSUE TITLE
Broken on Stable 4180

### ISSUE THREAD

**Issue by NoobToolzz** [n6333373/sublime-self-patcher#4]
I opened Sublime Text and it just had some exception and every element was distorted but the text area, my theme also removed. I ful reinstalled Sublime Text and the button (Patch this application) in the "Help" menu no longer shows.

**Comment by n6333373** [comment]
I won't help people to solve issues which are not related to this plugin here. Just go Sublime Text's forum/reddit/discord or wherever you consider helpful.

**Comment by n6333373** [comment]
Sounds like you are mixing `installed` ST with `portable` ST, which has a `Data` directory.

**Comment by NoobToolzz** [comment]
> Sounds like you are mixing `installed` ST with `portable` ST, which has a `Data` directory.

I only have Sublime Text installed, not portable. The app data directory for the "Packages" folder doesn't exist. Last time, I placed the plugin in the exe directory's "Packages" folder which worked. Now it doesn't. I'll attempt to redo this soon. 

The Sublime distortion was fixed by a reinstall, not a plugin issue. That was just context before the issue occurred.

**Comment by jfcherng** [comment]
Thanks for providing information but I don't think it's related to this repository anyway.

**Comment by NoobToolzz** [comment]
I found the "Packages" directory in appdata, but dragging self patcher into there and restarting does not work.

**Comment by n6333373** [comment]
> I found the "Packages" directory in appdata, but dragging self patcher into there and restarting does not work.

What's the folder name of self patcher? Can I assume that you have read the readme?
https://github.com/n6333373/sublime-self-patcher?tab=readme-ov-file#installation

If you think that the folder layout fits the following
```
Packages/
└── SelfPatcher/
    ├── boot.py
    ├── ...
```
then you can check whether there is any error message in Sublime Text console.

**Comment by NoobToolzz** [comment]
> > I found the "Packages" directory in appdata, but dragging self patcher into there and restarting does not work.
> 
> What's the folder name of self patcher? Can I assume that you have read the readme?
> https://github.com/n6333373/sublime-self-patcher?tab=readme-ov-file#installation
> 
> If you think that the folder layout fits the following
> ```
> Packages/
> └── SelfPatcher/
>     ├── boot.py
>     ├── ...
> ```
> then you can check whether there is any error message in Sublime Text console.

Folder layout was that. I did a full reinstall and the same steps then it worked again.
